In [1]:
import pandas as pd
df=pd.read_csv(r'C:\Users\USER\Downloads\HR_Analytics.csv')

In [2]:
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0.0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0.0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0.0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0.0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0.0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1480 entries, 0 to 1479
Data columns (total 38 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   EmpID                     1480 non-null   str
 1   Age                       1480 non-null   int64
 2   AgeGroup                  1480 non-null   str
 3   Attrition                 1480 non-null   str
 4   BusinessTravel            1480 non-null   str
 5   DailyRate                 1480 non-null   int64
 6   Department                1480 non-null   str
 7   DistanceFromHome          1480 non-null   int64
 8   Education                 1480 non-null   int64
 9   EducationField            1480 non-null   str
 10  EmployeeCount             1480 non-null   int64
 11  EmployeeNumber            1480 non-null   int64
 12  EnvironmentSatisfaction   1480 non-null   int64
 13  Gender                    1480 non-null   str
 14  HourlyRate                1480 non-null   int64
 15  JobInvolvement            1480 non-null   int64
 16  JobLevel                  1480 non-null   int64
 17  JobRole                   1480 non-null   str
 18  JobSatisfaction           1480 non-null   int64
 19  MaritalStatus             1480 non-null   str
 20  MonthlyIncome             1480 non-null   int64
 21  SalarySlab                1480 non-null   str
 22  MonthlyRate               1480 non-null   int64
 23  NumCompaniesWorked        1480 non-null   int64
 24  Over18                    1480 non-null   str
 25  OverTime                  1480 non-null   str
 26  PercentSalaryHike         1480 non-null   int64
 27  PerformanceRating         1480 non-null   int64
 28  RelationshipSatisfaction  1480 non-null   int64
 29  StandardHours             1480 non-null   int64
 30  StockOptionLevel          1480 non-null   int64
 31  TotalWorkingYears         1480 non-null   int64
 32  TrainingTimesLastYear     1480 non-null   int64
 33  WorkLifeBalance           1480 non-null   int64
 34  YearsAtCompany            1480 non-null   int64
 35  YearsInCurrentRole        1480 non-null   int64
 36  YearsSinceLastPromotion   1480 non-null   int64
 37  YearsWithCurrManager      1423 non-null   float64
dtypes: float64(1), int64(25), str(12)
memory usage: 439.5 KB

In [4]:
df.describe(include='all')

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1480,1480.000000,1480,1480,1480,1480.000000,1480,1480.000000,1480.000000,1480,...,1480.000000,1480.0,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1480.000000,1423.000000
unique,1470,NaN,5,2,4,NaN,3,NaN,NaN,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,RM1465,NaN,26-35,No,Travel_Rarely,NaN,Research & Development,NaN,NaN,Life Sciences,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2,NaN,611,1242,1042,NaN,967,NaN,NaN,607,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,36.917568,NaN,NaN,NaN,801.384459,NaN,9.220270,2.910811,NaN,...,2.708784,80.0,0.791892,11.281757,2.797973,2.760811,7.009459,4.228378,2.182432,4.118060
std,NaN,9.128559,NaN,NaN,NaN,403.126988,NaN,8.131201,1.023796,NaN,...,1.081995,0.0,0.850527,7.770870,1.288791,0.707024,6.117945,3.616020,3.219357,3.555484
min,NaN,18.000000,NaN,NaN,NaN,102.000000,NaN,1.000000,1.000000,NaN,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,30.000000,NaN,NaN,NaN,465.000000,NaN,2.000000,2.000000,NaN,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,NaN,36.000000,NaN,NaN,NaN,800.000000,NaN,7.000000,3.000000,NaN,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,NaN,43.000000,NaN,NaN,NaN,1157.000000,NaN,14.000000,4.000000,NaN,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,NaN,60.000000,NaN,NaN,NaN,1499.000000,NaN,29.000000,5.000000,NaN,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [29]:
print(df.dtypes)

emp_id                            str
age                             int64
age_group                         str
attrition                         str
business_travel                   str
daily_rate                      int64
department                        str
distance_from_home              int64
education                       int64
education_field                   str
employee_count                  int64
employee_number                 int64
environment_satisfaction        int64
gender                            str
hourly_rate                     int64
job_involvement                 int64
job_level                       int64
job_role                          str
job_satisfaction                int64
marital_status                    str
monthly_income                  int64
salary_slab                       str
monthly_rate                    int64
num_companies_worked            int64
over_time                         str
percent_salary_hike             int64
performance_rating              int64
relationship_satisfaction       int64
stock_option_level              int64
total_working_years             int64
training_times_last_year        int64
work_life_balance               int64
years_at_company                int64
years_in_current_role           int64
years_since_last_promotion      int64
years_with_curr_manager       float64
dtype: object

In [16]:
df.isnull().sum()

emp_id                        0
age                           0
age_group                     0
attrition                     0
business_travel               0
daily_rate                    0
department                    0
distance_from_home            0
education                     0
education_field               0
employee_count                0
employee_number               0
environment_satisfaction      0
gender                        0
hourly_rate                   0
job_involvement               0
job_level                     0
job_role                      0
job_satisfaction              0
marital_status                0
monthly_income                0
salary_slab                   0
monthly_rate                  0
num_companies_worked          0
over18                        0
over_time                     0
percent_salary_hike           0
performance_rating            0
relationship_satisfaction     0
standard_hours                0
stock_option_level            0
total_working_years           0
training_times_last_year      0
work_life_balance             0
years_at_company              0
years_in_current_role         0
years_since_last_promotion    0
years_with_curr_manager       0
dtype: int64

In [7]:
import re
df.columns = [re.sub(r'(?<!^)(?=[A-Z])', '_', col).lower() 
              for col in df.columns]

In [19]:
df.columns

Index(['emp_id', 'age', 'age_group', 'attrition', 'business_travel',
       'daily_rate', 'department', 'distance_from_home', 'education',
       'education_field', 'employee_count', 'employee_number',
       'environment_satisfaction', 'gender', 'hourly_rate', 'job_involvement',
       'job_level', 'job_role', 'job_satisfaction', 'marital_status',
       'monthly_income', 'salary_slab', 'monthly_rate', 'num_companies_worked',
       'over18', 'over_time', 'percent_salary_hike', 'performance_rating',
       'relationship_satisfaction', 'standard_hours', 'stock_option_level',
       'total_working_years', 'training_times_last_year', 'work_life_balance',
       'years_at_company', 'years_in_current_role',
       'years_since_last_promotion', 'years_with_curr_manager'],
      dtype='str')

In [13]:
df=df.rename(columns={'emp_i_d':'emp_id'})

In [15]:
df['years_with_curr_manager']=df['years_with_curr_manager'].fillna(df['years_with_curr_manager'].median())

In [33]:
df.drop(['monthly_rate'],axis=1,inplace=True)

In [42]:
df.drop(['employee_count'],axis=1,inplace=True)

In [43]:
df.columns

Index(['emp_id', 'age', 'age_group', 'attrition', 'business_travel',
       'daily_rate', 'department', 'distance_from_home', 'education',
       'education_field', 'employee_number', 'environment_satisfaction',
       'gender', 'hourly_rate', 'job_involvement', 'job_level', 'job_role',
       'job_satisfaction', 'marital_status', 'monthly_income', 'salary_slab',
       'num_companies_worked', 'over_time', 'percent_salary_hike',
       'performance_rating', 'relationship_satisfaction', 'stock_option_level',
       'total_working_years', 'training_times_last_year', 'work_life_balance',
       'years_at_company', 'years_in_current_role',
       'years_since_last_promotion', 'years_with_curr_manager',
       'experience_level'],
      dtype='str')

In [40]:
df['experience_level']=pd.cut(df['total_working_years'],bins=[0,2,5,10,40],labels=['Fresher', 'Junior', 'Mid', 'Senior'],include_lowest=True)

In [41]:
df.head()

,emp_id,age,age_group,attrition,business_travel,daily_rate,department,distance_from_home,education,education_field,...,relationship_satisfaction,stock_option_level,total_working_years,training_times_last_year,work_life_balance,years_at_company,years_in_current_role,years_since_last_promotion,years_with_curr_manager,experience_level
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,0,0,2,3,0,0,0,0.0,Fresher
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,0,0,2,3,0,0,0,0.0,Fresher
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,0,0,3,3,0,0,0,0.0,Fresher
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,0,0,2,3,0,0,0,0.0,Fresher
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,0,0,0,3,0,0,0,0.0,Fresher

In [44]:
df['attrition'].value_counts()

attrition
No     1242
Yes     238
Name: count, dtype: int64

In [47]:
pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\user\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: C:\Users\USER\AppData\Local\Programs\Python\Python314\python.exe -m pip install --upgrade pip

In [48]:
from sqlalchemy import create_engine

#mysql connection
username="root"
password="farzana90"
host="localhost"
port="3306"
database="hr_analytics"
engine=create_engine(f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}")

#write DataFrame to Mysql
table_name="employee_attrition"
df.to_sql(table_name,engine,if_exists="replace",index=False)

1480